# Generated by Django 2.1.7 on 2020-01-13 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=3000)),
                ('Image', models.ImageField(upload_to='images/')),
                ('Event_Date', models.DateField()),
                ('Event_type', models.CharField(choices=[('PB', 'Public'), ('PR', 'Private')], default='PB', max_length=2)),
                ('Participants_Limit', models.IntegerField(default=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participation_date', models.DateField()),
                ('mobile', models.IntegerField()),
                ('location', models.CharField(max_length=264)),
                ('event', models.ManyToManyField(related_name='participants', to='accounts.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
