# Generated by Django 2.1.7 on 2020-01-13 18:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='mobile',
        ),
        migrations.AddField(
            model_name='participant',
            name='mobileno',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
        ),
    ]
