# Generated by Django 2.1.7 on 2020-01-13 18:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200113_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='mobileno',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
